// <auto-generated />
using System;
using CR.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CR.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908123611_AddImageUrlToCar")]
    partial class AddImageUrlToCar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CR.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PriceFor8")
                        .HasColumnType("float");

                    b.Property<string>("Seats")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(1, 1, 1),
                            Fuel = "Gasoline",
                            Interior = "leathar",
                            Model = "Mercedes CLS 5.5 2020",
                            Price = 100.0,
                            PriceFor8 = 80.0,
                            Seats = "4",
                            StartingDate = new DateOnly(1, 1, 1),
                            Transmission = "Authomatic",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(1, 1, 1),
                            Fuel = "Gasoline",
                            Interior = "Fabric",
                            Model = "Mazda 6 2.0 2016",
                            Price = 70.0,
                            PriceFor8 = 50.0,
                            Seats = "5",
                            StartingDate = new DateOnly(1, 1, 1),
                            Transmission = "Authomatic",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateOnly(1, 1, 1),
                            Fuel = "Gasoline",
                            Interior = "leathar",
                            Model = "BMW X5 4.0 2018",
                            Price = 90.0,
                            PriceFor8 = 70.0,
                            Seats = "4",
                            StartingDate = new DateOnly(1, 1, 1),
                            Transmission = "Mechanical",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateOnly(1, 1, 1),
                            Fuel = "Diesel",
                            Interior = "Fabric",
                            Model = "Mecedes Viano 2.5 2021",
                            Price = 120.0,
                            PriceFor8 = 100.0,
                            Seats = "7",
                            StartingDate = new DateOnly(1, 1, 1),
                            Transmission = "Authomatic",
                            Type = "Van"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
